//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Net.Http.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Net.Http.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be greater than or equal to {0}..
        /// </summary>
        internal static string ArgumentMustBeGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("ArgumentMustBeGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A null &apos;{0}&apos; is not valid..
        /// </summary>
        internal static string CannotHaveNullInList {
            get {
                return ResourceManager.GetString("CannotHaveNullInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; of &apos;{1}&apos; cannot be used as a supported media type because it is a media range..
        /// </summary>
        internal static string CannotUseMediaRangeForSupportedMediaType {
            get {
                return ResourceManager.GetString("CannotUseMediaRangeForSupportedMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; type cannot accept a null value for the value type &apos;{1}&apos;..
        /// </summary>
        internal static string CannotUseNullValueType {
            get {
                return ResourceManager.GetString("CannotUseNullValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The media type formatter of type &apos;{0}&apos; does not support reading because it does not implement the ReadFromStreamAsync method..
        /// </summary>
        internal static string MediaTypeFormatterCannotRead {
            get {
                return ResourceManager.GetString("MediaTypeFormatterCannotRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The media type formatter of type &apos;{0}&apos; does not support reading because it does not implement the ReadFromStream method..
        /// </summary>
        internal static string MediaTypeFormatterCannotReadSync {
            get {
                return ResourceManager.GetString("MediaTypeFormatterCannotReadSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The media type formatter of type &apos;{0}&apos; does not support writing because it does not implement the WriteToStreamAsync method..
        /// </summary>
        internal static string MediaTypeFormatterCannotWrite {
            get {
                return ResourceManager.GetString("MediaTypeFormatterCannotWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The media type formatter of type &apos;{0}&apos; does not support writing because it does not implement the WriteToStream method..
        /// </summary>
        internal static string MediaTypeFormatterCannotWriteSync {
            get {
                return ResourceManager.GetString("MediaTypeFormatterCannotWriteSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No encoding found for media type formatter &apos;{0}&apos;. There must be at least one supported encoding registered in order for the media type formatter to read or write content..
        /// </summary>
        internal static string MediaTypeFormatterNoEncoding {
            get {
                return ResourceManager.GetString("MediaTypeFormatterNoEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No MediaTypeFormatter is available to read an object of type &apos;{0}&apos; from content with media type &apos;{1}&apos;..
        /// </summary>
        internal static string NoReadSerializerAvailable {
            get {
                return ResourceManager.GetString("NoReadSerializerAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object of type &apos;{0}&apos; cannot be used with a type parameter of &apos;{1}&apos;..
        /// </summary>
        internal static string ObjectAndTypeDisagree {
            get {
                return ResourceManager.GetString("ObjectAndTypeDisagree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configured formatter &apos;{0}&apos; cannot write an object of type &apos;{1}&apos;..
        /// </summary>
        internal static string ObjectContent_FormatterCannotWriteType {
            get {
                return ResourceManager.GetString("ObjectContent_FormatterCannotWriteType", resourceCulture);
            }
        }
    }
}
